repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        name: Fix end of files
        description: Ensures that a file is either empty or ends with one newline
        types: [text]
        exclude: ^src-tauri/gen/
      - id: trailing-whitespace
        name: Trim trailing whitespace
        description: This hook trims trailing whitespace
        types: [text]
        exclude: ^src-tauri/gen/
